### ISSUE TITLE
Don't hardcode weston-terminal in the init file

### ISSUE THREAD

**Issue by SnirkImmington** [way-cooler/way-cooler#122]
Currently we have soft dependencies on `weston-terminal` and `dmenu` (which itself depends on xwayland) in order to use basic features of Way Cooler. We should use a "find first match" in order to pick a _terminal_ instead of particularly a terminal. This would be an approach where we try some names of executables and the first one found we use. For example, we could change

``` lua
key({ mod }, "enter", "launch-terminal")
```

to

``` lua
key({ mod }, "enter", function() utils.exec.spawn_first_found("weston-terminal", "uxvrt", "xfce4-terminal", "xterm") end)
```

This would try `weston-terminal`, `uxvrt`, `xfce4-terminal`, and `xterm` in that order until one is found and launched.

Obviously we'd want to use different terminal names (look up the wayland supported ones first), and maybe a different name than `spawn.first_found`.

**Comment by Timidger** [comment]
Hmm, does `spawn_first_found` do the actual execution (because that's what it looks like it's doing)?

A simpler way might instead to do:
```
way_cooler.terminal = utils.find_first("weston-terminal", "uxvrt", "xfce4-terminal", "xterm")
```

and that way the correct terminal is found once (at start-up, so you don't suddenly change terminal emulators when you install/uninstall different ones). As well, that we wouldn't have to send a path to Lua just to spawn a program (and consequently no longer be able to do this if Lua was to suddenly die. If a bug occurs where the Lua thread is taken down it'd be nice to be able to get to a terminal to try and fix things)

**Comment by SnirkImmington** [comment]
> that way the correct terminal is found once (at start-up, so you don't suddenly change terminal emulators when you install/uninstall different ones and don't incur a lookup cost each time). 

Brilliant. I was just thinking about how it would be nice to be able to cache results from this, and that's the best approach. The result string can be passed off to other methods as well.

I think I'll add some `utils.exec` functions because we should be handling these keybindings from Lua.

> If a bug occurs where the Lua thread is taken down

So after initialization, the only times Lua errors will happen is ideally in some kind of callback (keybinding, timer, etc.). As long as we handle those properly, user errors wouldn't even propagate to the top of the Lua stack. But if they do, it's still in "interpreter" mode - any errors there will be received by the thread itself (we'll get some `Err` out of a `Result`) and execution should continue normally (as it receives requests). That's how it works right now.

If the Lua thread _panics_ for some reason, we could try restarting it (i.e. from the main thread or something).

**Comment by Timidger** [comment]
Ah that's a good point. Then the only issue I could see with any programs spawned from Lua would those that have been compromised by modifying how Lua sees the binaries / how the exec functions are executed (the simplest case being simply setting them to nil). There's probably ways to protect against that with meta tables, but ultimately there will always be issues with executing code from a potentially untrusted source.  

As time goes on, depending on what the Lua thread's role is post initialization, we might need to lock it down more heavily.

**Comment by SnirkImmington** [comment]
> Then the only issue I could see with any programs spawned from Lua would those that have been compromised by modifying how Lua sees the binaries / how the exec functions are executed (the simplest case being simply setting them to nil).

So the reasons I see for writing wrappers around `os.execute` and `io.popen` are
1. Convenience `exec` library (awesome has something similar), could consider the `find_first` to fall under this category
2. Hook into the "don't zombificate child processes" way-cooler code (unless Lua could handle that for us)
3. Window manager specific uses - show spinney cursor while program is launching, or a popup when it's launched/failed/command-not-found (probably available via IPC too)
4. Lua should have special methods to spawn new clients with client perms (another IPC method)

Lua's `os.execute` on its own won't be an issue - we wouldn't give Lua access to any actual IPC client auth tokens anyway.

> ultimately there will always be issues with executing code from a potentially untrusted source.
> As time goes on, depending on what the Lua thread's role is post initialization, we might need to lock it down more heavily.

I will open another issue about how much power the Lua session should have and how clients should interact with it.

**Comment by Timidger** [comment]
>So the reasons I see for writing wrappers around os.execute and io.popen are...

I wasn't trying to imply we shouldn't write these wrappers, if anything they would be very helpful from both an ease of use and security stand point. I just want to nail down exactly how much untrusted code we are going to be executing and what user programs could do (and how to minimize/eliminate any havoc)

>  2. Hook into the "don't zombificate child processes" way-cooler code (unless Lua could handle that for us)

To make a process not zombiefied, you just need to check the return code from the process. This usually entails wrapping it in another process (e.g like how we did with `sh`)

>  3. Window manager specific uses - show spinney cursor while program is launching, or a popup when it's launched/failed/command-not-found (probably available via IPC too)

Small correction, clients draw the cursor in Wayland so that would potentially be a bit more complicated (and probably impossible) unless the user is focused on a view where we can control it (e.g the background). If we could only implement a half-assed solution in that case it would probably better not to do so at all.
