### ISSUE TITLE
Awesome style tiling

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#138]
* Lua function that takes in the geometry limits of the container and the list of views. Returns an array of geometries that map from each container in the list to the geometry in the returned array.
* Lua Containers can not be the root container.
* If the function errors or otherwise returns bad output, destroy the Lua Container and push the children to the parent container (guaranteed to be a container).
* Can nest i3-style in Lua-style, and can also nest Lua-style in Lua.

**Comment by Yamakaky** [comment]
I would love it. I prefer the awesome tags to the i3 workspace, it's more flexible.

**Comment by SnirkImmington** [comment]
> I prefer the awesome tags to the i3 workspace, it's more flexible.

This issue is about writing Lua scripts to lay out windows within a container, i.e. to tile/lay out windows without manipulating containers directly. Being flexible about workspaces/tags is discussed in https://github.com/Immington-Industries/way-cooler/issues/105.

**Comment by Timidger** [comment]
@Yamakaky, thanks for your input, awesome tags will take quite a bit of work so I'm unsure where to fit them in the timetable. Since it's such a big change, I will look into doing it sooner (and breaking less things) rather than later. I need to rewrite the workspace code anyways, it has a lot of issues.

**Comment by Timidger** [comment]
In order to better support the awesome work flow, I think the best way to support the "tiling modes" from awesome is to specify them in a table in the init file. I'm thinking something like this:

    -- awesome-style tiling mode table
    {
        -- This is the layout that has a "main" window on the left
        -- with every other window on the right
        -- TODO need a better name for this...
        "main-left": main_left_layout,
        "main-right": main_right_layout,
        ...
    }

    -- awesome-style tiling mode implementations
    function main_left_layout(geometry, views)
        local result = [];
        local first_view = views[1];
        local first_geometry = {
            "origin": { 
                "x": geometry.origin.x
                "y": geometry.origin.y
            },
            "size": {
                "w": geometry.size.w / 2,
                "h": geometry.size.h / 2
            }
        }
        first_view[1] = first_geometry;

        local length = -1;
        for i in pairs(views) do
            length += 1;
        end

        for i, v in ipairs(views) do
            if (i == 0) break;
        result[i] = {
            "origin": { 
                "x": geometry.origin.x + geometry.size.w / 2,
                "y": geometry.origin.y + geometry.size.h / (length - i) + 1
            },
            "size": {
                "w": geometry.size.w / 2,
                "h": geometry.size.h / length
            }
        }
        end
        return result;
    end

The key in the table would be the name that is associated with the tiling mode (so that it can be switched to explicitly, either in a keybinding command or a client. This name is also what will appear in the title portion of the server side borders). The value is the function that calculates the geometries of the views of the container.

Some (very rough) code is given as an example, but that's what the tiling code should ultimately look like. The function will take in the geometry bounds of the container, and a list of all the views. The job of the function is to return an array of geometries which are "mapped" to each element in the view. Notice in the example code we treat the first one as special (it takes up the complete left side) and the rest are just evenly dispersed on the right side.

It can always be assumed that that the number of views in the list >= 1. A container can usually not be empty, however that does not apply for the root container. In those cases though, Way Cooler will not bother delegating layout to lua functions because its obvious that the only solution is to return `[]`. This will reduce the amount of boilerplate present in the lua functions.

@SnirkImmington, thoughts? I don't know how awesome does it, if there is a better way that either they do it or anything you're thinking of I'd like to hear it.

**Comment by SnirkImmington** [comment]
A couple of ideas for Lua setup:

We should definitely be providing a lot of the default Lua tiling algorithms. This was actually a part of awesome that I never touched because it just worked. The way awesome set it up, you have several layout types, like `columns` or `rows` and you'd have variants (usually left-preference vs right-preference or top-preference vs bottom-preference).

For example, my terminal setup was columns with left preference - that way spawning 2 terminals would split them into columns, and once a third was spawned the first two would go to the left column and the third on the right column. The "column right-preference" layout would be mirrored. The `rows` layouts would also be the same thing but making rows and top vs bottom oriented.
The advantages we get with Lua are mostly about not manipulating subcontainers: choose a different layout mode to lay things out differently, and allow the layout theme to handle placement of windows (user input is just choose theme and re-order windows in the list).

I kind of had an idea for this with the workspace configuration part of the init file:
```lua
-- The default layout options are no names, mode = "default" (use keybindings).
-- For a list of tiling options, see way-cooler docs or `man way-cooler-tiling`.
-- Workspaces, like arrays in Lua, start with 1.
local workspace_settings = {
  -- The first workspace is named web
  [1] = { name = "web" },
  -- The 9th workspace is named "free", and all windows sent there float.
  [9] = { name = "free", mode = "float" },
}
-- Create 9 workspaces with the given settings.
config.init_workspaces(workspace_settings)
```

Assuming we provide some layout types (I'd write at the least, an equivalent to the `columns` and `rows`) that could go in workspace initialization. You'd be able to toggle/cycle/choose layout type per container, but the workspace settings would choose the default layout/layout for the root container of the workspace.

Another issue is floating - I think it's more useful in some cases to say "float this workspace" (i.e. when working with gimp and its floating toolbars) than "float this view" - and we should offer that as a layout type. We'd need a way to make this work with existing floating options _and_ Lua-defined layout schemes, though.

**Comment by Timidger** [comment]
`workspace_settings` will be a fine place to put the layout mode. That will set the default mode for the root container of the workspace. You can change the mode, but if the workspace is destroyed (eg, you remove all the windows and then move out and then back in the workspace) it will be regenerated with the original mode that is set in the configuration.

I don't really want to add the "float mode" because right now floating containers are a special case in the tiling. They are views that are children of the root container that have a special flag set. They are basically exempt from tiling all together. Eg, popup windows such as dmenu fall in this case as well. 

I can write a mode where everything is just made floating, but frankly if that's the use case of someone they shouldn't be using a tiling window manager. For special case applications like gimp, they can always just specify a rule in their config that will make that window floating. (ultimately, this might be something that you can do through rules anyways, so if you still want this feature I'll probably just let it do-able through rules)

**Comment by Timidger** [comment]
Blocked until we get #72 added, since it would be a little difficult to tell which tiling you're using other wise (also that's more important)

**Comment by Timidger** [comment]
See #338
