### ISSUE TITLE
Populate the config file by default

### ISSUE THREAD

**Issue by colemickens** [way-cooler/way-cooler#215]
AFAICT I have to manually copy the file from GitHub or the repo into the desired location. It'd be nifty if way-cooler just dropped it there by default so I could just make edits to it.

**Comment by Timidger** [comment]
I have had the exact same thought :).

What I plan to do way way in the future (v0.6 or v0.7) was to have a little popup (similar to how i3 does) prompting to save it and with different defaults (e.g modifier, color scheme, etc.). For now though, I can just handle the simple case of writing the file out if it's not detected.

This functionality will _probably_ have to be modified come 0.5 though -- we will be making the "init file" only runnable from `/etc/` and putting the configuration options that don't need a full blown lua environment into something like `$XDG_HOME/way-cooler/config.yaml`. At that point writing the init file to `/etc/` would become harder because we would need a prompt for password (and thus some sort of dialog to prompt for it).

**Comment by colemickens** [comment]
> we will be making the "init file" only runnable from /etc/

Wait, why is this? I like that any user can use way-cooler today without needing root. It seems like that change would prevent that from happening?

**Comment by Timidger** [comment]
I've thought about this a lot, and here's my reasoning (and feel free to tell my this is a mistake -- it's possible it is!)

Both Wayland and Rust are designed around the idea that security is very important. Too much software these days doesn't take this into account. This is especially important for something with a large attack vector as a window manager designed to be as extendable by the user as possible.

The main way we will control the security of the window manager is by assigning permissions to client programs through the `init.lua`. Clients will need to request permission for things that in X11 you could just do freely (such as kill windows, get information about other windows, get pointer position, etc.). 

However, if the `init.lua` file is in a path that is writeable by the user, a malicious script could inject permissions into the file and basically gain control of the window manager. 

My solution is to move `init.lua` into `/etc/` and move *most* of the configuration options into a yaml file in `$XDG_HOME/way-cooler/config.yaml`. E.g colors, border size, gap size, etc. Basically the things that users would want to change on a regular basis.

However, both keybindings and client permissions would live in `/etc/init.lua`. They are the largest attack vectors, and also the things that are most rarely changed.

My reasoning is if the user really wants a Lua file in a user writable path, they can add `require("/path/to/insecure/lua/file.lua")` at the end of their `/etc/way-cooler/init.lua` file.

I think it's possible to remain highly configurable, but also be very secure at the same time with this setup.

I have come up with a few alternative, but they are more complicated and also less secure:

* Having two lua files, one for client permissions (in `/etc/`) and another for keybindings (in `$XDG_HOME`)
* Caching permissions in a root file somewhere and prompting the user when a new one is added.

**Comment by Timidger** [comment]
For anyone coming from the future: My previous comment is no longer the plan for Way Cooler. See the discussion at #219 for more details.
