### ISSUE TITLE
Set keymap

### ISSUE THREAD

**Issue by pExeen** [way-cooler/way-cooler#311]
Hello I would like to know if there is a way to the keyboard map.

Sorry if I just didn't see it.

**Comment by pExeen** [comment]
Sorry I didn't know that wlc takes care of this..

So just use this of exemple :
`export XKB_DEFAULT_LAYOUT=de`

And super project by the way :)

**Comment by Timidger** [comment]
Thanks, I should probably document that in a better place though...it's easy to miss that, especially since it depends on an internal detail of how Way Cooler is implemented. No where good to put it quite yet, probably eventually somewhere on the [website](http://way-cooler.org) once I have a "getting started" page or something.
