### ISSUE TITLE
Fix dbus docs

### ISSUE THREAD

**Issue by amon-ra** [way-cooler/way-cooler#325]
I have trying to connect using dbus but, for example, on arch there is no pydbus. I have to use import dbus.

The first example in docs could be: 
```
import dbus
bus = dbus.SessionBus()

layout = bus.get_object(bus_name='org.way-cooler', object_path='/org/way_cooler/Layout')

active_id = layout.ActiveContainerId(dbus_interface='org.way_cooler.Layout'))


#dbus-send --session --print-reply --type=method_call --dest=org.way-cooler /org/way_cooler/Layout org.way_cooler.Layout.ActiveContainerId
 ```
Last line is the call using dbus-send program

**Comment by Timidger** [comment]
You should install `pydbus` using `pip` (I'm also using Arch).

Since there is no dbus library in the standard library, I went with what I saw was the most popular / best maintained.

I'll be adding more ways to represent the examples in the future though. I'll probably target Lua, Ruby, Rust, and the shell (e.g with the dbus-send you showed).

If you'd like to help though, feel free to open a PR adding the shell examples in the docs or add a disclaimer somewhere that for the python examples the user should install `pydbus`.

**Comment by amon-ra** [comment]
Ok. Thanks
