### ISSUE TITLE
Way Cooler README overhaul

### ISSUE THREAD

**Issue by platipo** [way-cooler/way-cooler#341]
I saw the [new branch readme-prettify](https://github.com/way-cooler/way-cooler/tree/readme-prettify) and thought that would be the right occasion to add to the README.md some clarifications of he Way Cooker ecosystem:
- [line 45](https://github.com/way-cooler/way-cooler/commit/48bb1a401de562809437ece69d25318d5da9edfb#diff-04c6e90faac2675aa89e2176d2eec7d8L45): the link to [way-cooler-grab](https://github.com/way-cooler/way-cooler-grab)
- [line 46](https://github.com/way-cooler/way-cooler/commit/48bb1a401de562809437ece69d25318d5da9edfb#diff-04c6e90faac2675aa89e2176d2eec7d8L46): the link to [way-cooler-lock](https://github.com/way-cooler/way-cooler-lock)
- [line 47](https://github.com/way-cooler/way-cooler/commit/48bb1a401de562809437ece69d25318d5da9edfb#diff-04c6e90faac2675aa89e2176d2eec7d8L47): the link to [way-cooler-bg](https://github.com/way-cooler/way-cooler-bg) with a little description
- [line 76](https://github.com/way-cooler/way-cooler/commit/48bb1a401de562809437ece69d25318d5da9edfb#diff-04c6e90faac2675aa89e2176d2eec7d8L76): `dwnload` typo
- [lines 103-116](https://github.com/way-cooler/way-cooler/commit/48bb1a401de562809437ece69d25318d5da9edfb#diff-04c6e90faac2675aa89e2176d2eec7d8L103): links to contributor profiles 

Or add a new section to point out the existence of these programs, their importance/function and how to integrate the in the workflow.

**Comment by Timidger** [comment]
Good idea! I mostly made that branch last night because I knew I wanted to make some readme changes in the near future (the current one is stale, and somewhat out of date), but it was made mostly so I could play with displaying the logo last night without dirtying up the master branch.

What I'll probably do is re-do the entire structure of it in order to highlight Way Cooler as usable rather than an in-progress hobby project (this is most evident with my /\*todo\*/ list being finally shorter than my "current feature" list).

So I'll probably have a list near the top of all the extensions to Way Cooler. I will move other things around, either to separate pages or to the website (e.g: the list of features will probably move to a page on the website similar to how [sway does it](http://swaywm.org/roadmap)).

If you think there's anything I should add or remove (I will develop this branch for a while as I prepare for 0.7, which will be pretty big since I'm planning on add awesome support), feel free to open a PR on it or post a comment here.

**Comment by platipo** [comment]
Great! I found very usefull reading the [art of README](https://github.com/noffle/art-of-readme), maybe it could provide some nice starting point for the rewrite.

Also it would be better to change issue title with a less specific one so others can contribute

**Comment by Timidger** [comment]
Gonna remove the 0.7 requirement, since this is something I want to do pre awesome compatibility since that will drastically change the marketing aspects of Way Cooler

**Comment by arsdragonfly** [comment]
could you mention that way-cooler depends on awesomewm Lua libraries? Instructions on copying the config file to ~/.config/way-cooler would be helpful as well.
