### ISSUE TITLE
Ungrabbing for key bindings

### ISSUE THREAD

**Issue by z33ky** [way-cooler/way-cooler#342]
I've written a small extension with which you can easily add modal window managing, inspired by modal text editing à la vi.
It works something like this:
```
normal = Mode.new("normal")
move = Mode.new("move")

normal:add({
  key({ mod }, "m", move:mode()) --Mode.mode() returns a function
})

move:add({
  key({ }, "h", "move_active_left"),
  ...
  key({ }, "return", normal:mode()) --"escape" is also bound to return to normal mode by default
})
```

For this I need to add the binding of the "h"-key when entering move-mode, and remove it when leaving.
Currently I set it to a noop-function, which obviously also blocks the "h"-key from working normally, since it is grabbed by way-cooler.

I see two solutions to this.

The simpler solution would allow unregistering key bindings.
On a mode-switch I also need(/want) to remove all key bindings of the current mode, which means that every mode-switch comes with a slew of unregistering and registering keys. I don't know if that's a good thing to do, performance-wise, since I expect some kind of associative data-structure is used for this.

This brings me to my second solution: Allowing the lua-callbacks to signal whether the pressed key should be swallowed or passed through to the active window. This could be achieved by allowing the callbacks to return a boolean, indicating what behavior is desired.
With this I would also not need to have a slew of unregistering and registering keys on mode-switches. I could simply assign a different callback to already registered keys, so the mapping data-structure does not need to add and remove a bunch of keys, just change some values.

**Comment by Timidger** [comment]
Oh wow, I'll be honest when I added the feature I feared it wouldn't used in its current form, but nice job turning Way Cooler into a modal editor! 

How about I actually just add both features? I'll add a method to unregister a keybinding (given a key, because, as you correctly guessed, I use a hash map to associate keys to their commands) and I'll add a flag to the key method (just after the fourth `loop` argument which is rarely used) that is false by default and when true will allow pass through. 

I can see both features being useful, and they are both backwards compatible. Both are simple enough I can add them in 0.6.1.

**Comment by z33ky** [comment]
> Oh wow, I'll be honest when I added the feature I feared it wouldn't used in its current form

Do you mean the Lua-callbacks? Are there plans to change the way it works?

> but nice job turning Way Cooler into a modal editor!

I was actually kind of surprised that I couldn't find this sort of key configuration in any of the tiling WMs.
Then again, there also seem to be very few people who use the `bindkey -v`.

Mainly it lacks a way to display what mode is currently active.
I'll clean the code a little bit put it in a repo. Maybe someone will stumble upon it and find it useful.

> How about I actually just add both features? I'll add a method to unregister a keybinding (given a key, because, as you correctly guessed, I use a hash map to associate keys to their commands) and I'll add a flag to the key method (just after the fourth loop argument which is rarely used) that is false by default and when true will allow pass through.

Sounds good to me.

> I can see both features being useful, and they are both backwards compatible. Both are simple enough I can add them in 0.6.1.

Agreed.
I'm happy to get this feature soon. I might actually attempt the switch to Wayland then :)

**Comment by Timidger** [comment]
> > Oh wow, I'll be honest when I added the feature I feared it wouldn't used in its current form
> 
> Do you mean the Lua-callbacks? Are there plans to change the way it works?

Whoop' s that was a type (I should stop replying to comments before I have my morning coffee). I meant to say I feared wasn't going to be *useful* in its current form. My plan was to extend it in some way, but I'm not sure what the plan is now ever since I decided on #338.

> Mainly it lacks a way to display what mode is currently active.
Yeah that's something that can only really be done well with a integrated/official status bar. That's planned, but will not come until next year probably since my work schedule is very, very intense right now. If someone was to implement one though, I can work with them to make sure Way Cooler exposes all the information it needed over e.g D-Bus.
