### ISSUE TITLE
Some applications doesn't work

### ISSUE THREAD

**Issue by Applemann** [way-cooler/way-cooler#357]
@Timidger  Hello I tried start some various applications via `dmenu` but some apps doesn't work.. (gnome-terminal, krusader, gedit..)
Why?

Also I tried start way-cooler in my computer with ubuntu and xserver. There way-cooler start in window and works fine.
But when I start it in another tty where I log in and run: `way-cooler` in console -> so way-cooler doesn't show background, arrow is black (not white) and starting applications is very very slow.. (thunar)
Is it OK??

**Comment by Timidger** [comment]
Assuming you have xwayland installed (which it sounds like you do, since `thunar` works)  please double check that your xdg-shell version matches what Way Cooler uses (v6) by doing `ls -l /usr/share/wayland-protocols/unstable/xdg-shell/`. You should have a `xdg-shell-unstable-v6.xml` file in there. If you don't, please install it (I'm not sure if it's in the main repos for Ubuntu, but you might be able to find a PPA of it somewhere. You can also try to install it manually).

Way Cooler not showing the background is interesting, are you sure you have `way-cooler-bg` installed (e.g does `which way-cooler-bg` work?). The arrow will be black, because that's the default that Wayland uses (and that currently I can't change, for various reasons).

I would check other applications if `thunar`'s start time is slow, I found that not all apps work equally well when using xwayland. If you notice that the compositor itself is sluggish (e.g mouse moving or otherwise) that's a different problem (if you compiled from source, did you make sure to pass the `--release` flag to `cargo` to ensure it's not running in debug mode?)
