### ISSUE TITLE
Resizing is not as performant as 5.x

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#371]
An issue I've noticed when comparing Way Cooler 0.6.x to 0.5.2 (which I still run on my other laptop) is that it's much laggier to resize containers. This is probably a result of full-scale tiling being done on each geometry change, which needs to be investigated and fixed. The problem is much worse the more windows you have on the screen.

**Comment by Arnaz87** [comment]
A posible cause of this problem is [this section of code](https://github.com/way-cooler/way-cooler/blob/master/src/layout/core/container.rs#L620-L634). The test always fails because [relocate_buffers](https://github.com/way-cooler/way-cooler/blob/master/src/layout/core/borders/borders.rs#L96) always modifies the geometry (to account for the borders and title) before saving it.

**Comment by Timidger** [comment]
I will investigate @Arnaz87 report more closely tonight.

**Comment by Timidger** [comment]
After testing it by changing the geometry comparison so that it occurs with the changes applied, I did not notice a big change in performance. Although, I tried to test 0.5.2 and I noticed it seem laggier than I remember.

Since, long term, I expect this tiling system to be done away with in favour of the tiling system of awesome in Lua I'm going to go ahead and close this as WONTFIX.

If someone else finds a solution and supplies a patch, I'd be more than happy to merge it. However, it's not worth me looking into at this time.
