### ISSUE TITLE
J4-dmenu-desktop with options doesn't seem to work

### ISSUE THREAD

**Issue by that1communist** [way-cooler/way-cooler#437]
`  key({ mod4 }, "period", util.program.spawn_once("j4-dmenu-desktop --no-generic --term="termite" --dmenu="dmenu -f -nf '#ffffff' -nb '#000000' -sb '#d32f2f' -sf '#ffffff' -i -fn 'Noto Mono'"")),`

is my dmenu command, which works fine on i3

`bindsym mod4+period exec --no-startup-id j4-dmenu-desktop --no-generic --term="termite" --dmenu="dmenu -f -nf '#ffffff' -nb '#000000' -sb '#d32f2f' -sf '#ffffff' -i -fn 'Noto Mono'"`

on way-cooler it tells me

` SyntaxError("[string \"chunk\"]:69: \')\' expected near \'termite\'") `

unless i'm missing something, it doesn't seem to work.

**Comment by Timidger** [comment]
> `key({ mod4 }, "period", util.program.spawn_once("j4-dmenu-desktop --no-generic --term="termite" --dmenu="dmenu -f -nf '#ffffff' -nb '#000000' -sb '#d32f2f' -sf '#ffffff' -i -fn 'Noto Mono'"")),`

Is it just me or do you have an extra `"` in there at the end.

Either way, it looks like you're not escaping your `"` correctly. Since this is a string in Lua, you need to escape them with `\"`. So your command will be:

`key({ mod4 }, "period", util.program.spawn_once("j4-dmenu-desktop --no-generic --term=\"termite\" --dmenu="dmenu -f -nf '#ffffff' -nb '#000000' -sb '#d32f2f' -sf '#ffffff' -i -fn 'Noto Mono'")),`

**Comment by that1communist** [comment]
Just checked, no extra quote.

But yeah that was the problem... thank you, sorry, about that.
