### ISSUE TITLE
lemonbar config

### ISSUE THREAD

**Issue by gnidorah** [way-cooler/way-cooler#446]
Hi!
Could you please add lemonbar config seen on screenshots to the way-cooler repo?
I want to make out-of-box experience on NixOS better, and that will be the first step :)

**Comment by Timidger** [comment]
I think you didn't delete the pre-filled issue template, you might want to edit your comment.

As to your actual question: I wasn't planning on adding it to this repo as lemonbar is not the official status bar of Way Cooler (and there eventually will be one, namely the AwesomeWM one).

However, I'll still happily upload it here so you can use it in your package.

**Comment by Timidger** [comment]
Shell script (just the starter): [bar.sh](https://github.com/way-cooler/way-cooler/files/1529700/bar.sh.txt)
Python script (does the dbus work): [bar.py](https://github.com/way-cooler/way-cooler/files/1529701/bar.py.txt)

Script requires Python 3 and pydbus.

**Comment by gnidorah** [comment]
@Timidger Thank you much!
Here's what NixOS users will get out of box after https://github.com/NixOS/nixpkgs/pull/32285 :-)
![screenshot](https://user-images.githubusercontent.com/12064730/33628523-08593994-da12-11e7-8e37-e7aa3ccf8ce2.png)

**Comment by gnidorah** [comment]
@Timidger The only issue left is that the bar sometimes appears at the center of screen instead of the top. Is it a known bug?

**Comment by Timidger** [comment]
It's a bug I've sometimes noticed on _some_ machines _sometimes_ -_-. 

I _think_ it's a race condition, but I'm not sure. If you can find a nice way to reproduce it that would be excellent. One thing that might help is adding a "sleep" so that when the top bar is spawned it's after Way Cooler has fully started it and it can "catch" it as the top bar.

**Comment by Timidger** [comment]
To add on to the previous comment: X bar support is a bit of a hack and the long term solution is to wait until Way Cooler has a dedicated bar via Awesome support

**Comment by gnidorah** [comment]
@Timidger Thanks, that does the trick! Yes, I understand, nevertheless it's good enough for temporary solution :)

**Comment by Timidger** [comment]
@gnidorah Just a heads up I noticed there was a crazy amount of CPU usage from Way Cooler recently..and I tracked it down to the configuration I used in lemonbar. Doing a D-Bus call every milisecond is very slow. I reduced it to 1 sec on my machine, but it does feel less responsive. So that's something you might want to consider for the users of the NixOS package.
