### ISSUE TITLE
AwesomeWM: To replace/override type() or not?

### ISSUE THREAD

**Issue by psychon** [way-cooler/way-cooler#466]
AwesomeWM replaces Lua's `type` function so that e.g. `type(screen[1])` will return "screen" (see `luaAe_fixups` and `luaAe_type` in `luaa.c`). In way-cooler, this will result in "table" instead.

This breaks e.g. the compatibility stuff in `awful.taglist.new`: In older versions of awesome, this function got six arguments which all were basically optional. These days it gets a table instead in which it looks up its arguments. Based on `type(first_argument) == "screen"` it provides backward-compatibility with the old arguments list. Since the `rc.lua` that comes with way-cooler uses an old-style call... well, I got a cryptic error about `table index is nil` in a line that used a screen as a table index because the code tried to use `argument.screen` as the screen, where `argument` was already supposed to be a screen.

**Comment by Timidger** [comment]
Hmm, that is a problem.

I'm hoping that we can eventually have the same structure as old awesome if [the points I made in this old issue are addressed](https://github.com/chucklefish/rlua/issues/41). Since there's little response there (unsurprising with the holiday season, and it is an old "solved" issue) I'm thinking I'm might try to tackle it next week and send a pr to them. The main thing is trying to achieve it safely, since it won't be merged if it exposes a safety hole in the library.

If that doesn't work out, there probably is a way we can get the custom type checking working with the table. I'd rather fix the underlying structure though, because I think this issue is going to keep coming up for us otherwise.

**Comment by Timidger** [comment]
This should be fixed thanks to [this change in rlua](https://github.com/chucklefish/rlua/issues/41#issuecomment-360931848). We just need to propogate it here by changing how we store the types as uservalues rather than the tables. Then we don't need to override `type`.

**Comment by psychon** [comment]
>  Then we don't need to override type.

Uhm, yes, you do. As far as I know, Lua's built-in `type` always identifies userdata as `"userdata"`. That's why awesome explicitly overwrites `_G.type` with its own function.

**Comment by Timidger** [comment]
Whoops, sorry. Read this issue too quickly last night and obviously wasn't awake enough.

Yes we'll still need to override `type`

**Comment by psychon** [comment]
This should be fixed by 50037636386c24362f7eee373672e628d20178e4. Sorry, I forgot to refer to this issue in the commit message.
