### ISSUE TITLE
Support "Lock" in mods_to_rust

### ISSUE THREAD

**Issue by psychon** [way-cooler/way-cooler#483]
I had to do https://github.com/way-cooler/way-cooler/pull/482/commits/f6bbd39ebea4a40f9e1192dc4bbb8788f2df9684#diff-c235587ce0bce2115a4765667de27acbR41 because otherwise the awesome default config does not load. The reason is that `lua::utils::mods_to_rust` does not understand `Lock`.

The corresponding function in awesome is here: https://github.com/awesomeWM/awesome/blob/4ad516c63a1c0426e2ee80373d5abc8f44657ad0/common/xutil.c#L31. It translates `Lock` to `XCB_MOD_MASK_LOCK`. I have no idea what `Lock` corresponds to in wlc (and I am not even sure what this is in X11, numlock?).

Apparently, the following constants with prefix `MOD_` exist in rustwlc (the string afterwards is which string must be passed to `mods_to_rust` to get this modifier):

- `rustwlc::types::MOD_ALT`, "Alt"
- `rustwlc::types::MOD_CAPS`, "Caps"
- `rustwlc::types::MOD_CTRL`, "Control"
- `rustwlc::types::MOD_MOD2`, "Mod2"
- `rustwlc::types::MOD_MOD3`, "Mod3"
- `rustwlc::types::MOD_MOD4`, "Mod4"
- `rustwlc::types::MOD_MOD5`, "Mod5"
- `rustwlc::types::MOD_SHIFT`, "Shift"
- `rustwlc::types::MOD_NONE`

In awesome, `xutil_key_mask_fromstr` supports the following constants:

- `XCB_MOD_MASK_SHIFT`, "Shift"
- `XCB_MOD_MASK_LOCK`, "Lock"
- `XCB_MOD_MASK_CONTROL`, "Control", "Ctrl"
- `XCB_MOD_MASK_MOD1`, "Mod1"
- `XCB_MOD_MASK_MOD2`, "Mod2"
- `XCB_MOD_MASK_MOD3`, "Mod3"
- `XCB_MOD_MASK_MOD4`, "Mod4"
- `XCB_MOD_MASK_MOD5`, "Mod5"
- `XCB_BUTTON_MASK_ANY`, "Any"

So... `Lock`, `Ctrl`, `Mod1`, and `Any` are missing from `mods_to_rust` while `Alt` and `Caps` are things that `mods_to_rust` can do, but awesome does not understand. Based on this, what do you think about the following patch? (I have no idea what `Any` is supposed to do nor what `NONE` is doing)
```diff
diff --git a/src/lua/utils.rs b/src/lua/utils.rs
index 732b277..4107e0d 100644
--- a/src/lua/utils.rs
+++ b/src/lua/utils.rs
@@ -39,13 +39,14 @@ pub fn mods_to_rust(mods_table: Table) -> rlua::Result<KeyMod> {
     for modifier in mods_table.pairs::<Value, String>() {
         match &*modifier?.1 {
             "Shift" => mods.insert(MOD_SHIFT),
-            "Caps" => mods.insert(MOD_CAPS),
-            "Control" => mods.insert(MOD_CTRL),
-            "Alt" => mods.insert(MOD_ALT),
+            "Lock" => mods.insert(MOD_CAPS),
+            "Control"|"Ctrl" => mods.insert(MOD_CTRL),
+            "Mod1" => mods.insert(MOD_ALT),
             "Mod2" => mods.insert(MOD_MOD2),
             "Mod3" => mods.insert(MOD_MOD3),
             "Mod4" => mods.insert(MOD_MOD4),
             "Mod5" => mods.insert(MOD_MOD5),
+            "Any" => mods.insert(MOD_NONE),
             string => {
                 use rlua::Error::RuntimeError;
                 Err(RuntimeError(format!("{} is an invalid modifier", string)))?
```
(Feel free to commit this patch if you think it is the right thing to do, but somehow I do not really feel so)

**Comment by Timidger** [comment]
For backwards compatibility you should be treating `"Caps"` as `MODS_CAPS` as well.

As with `"Any"` I'm _assume_ that's supposed to mean any type of modifiers can be held down and the key should trigger whatever it triggers.

Assuming I understand that correctly, that's not something we currently support in Way Cooler key lookups since we check that the modifier is exactly equal to what we store.

More specifically, [here is the type we store in the global hashmap from key presses -> actions we do with them](https://github.com/way-cooler/way-cooler/blob/master/src/keys/keypress.rs#L15). It derives equality, which on the bitfield means it has to be exactly equal. 

There's various ways we can fix that to make it work, the most "correct" way I can think of is to change what `KeyPress` stores so it's an `enum` with either a type for "any" of them or a specific type of modifier:

```rust
enum MaybeMod {
    /// Doesn't matter what's held down, this will match as any
    Any,
    /// Actually match against 0 or more modifiers (e.g no modifier pressed down, just caps, etc.)
    Mod(KeyMod)
}
```

This will require more invasive changes. The other option is to expand the bitfield, but I'm not ok with that because it requires modifying rustwlc and further ties us to it (and would require a rewrite anyways when we switch to wlroots).

So with that change, eliding the other changes necessary for this, the "Any" case would become:

```rust
match &*modifier?.1 {
    ...
    "Mod5" => mod.insert(MOD_MOD5),
    "Any" => return MaybeMod::Any
}
return MaybeMod::Mod(mod);
```

**Comment by psychon** [comment]
I took the lazy approach: I added the aliases for the existing modifiers in #484. Before I dig into input handling, I'll wait for wlroots-rs to happen. X11 input handling already scared me enough in the past, sorry.

While that fixes this issue, perhaps a new one for `Any` should be opened?

**Comment by Timidger** [comment]
Sounds good, I don't blame you for holding off. I'll have a better time table for wlroots-rs soon.

Yeah I'll make another issue for the Any case

**Comment by psychon** [comment]
Thanks!
