### ISSUE TITLE
Awesome objects' should implement to string correctly

### ISSUE THREAD

**Issue by Timidger** [way-cooler/way-cooler#498]
Currently we don't do anything fancy with the object tostring method. We should emulate awesome and print the name of the object.

**Comment by psychon** [comment]
How close to awesome do you want to be?
```
$ awesome-client 'return button{}, client.focus'
   string "button: 0x55ff58fd1d98"
   string "window/client(x-terminal-emulator): 0x55ff582e0638"
```
This prints the memory address of the object, which is something that rlua does not let us access, I think. Also, this prints an implementation detail of the C code: there is a `window` class that is the parent for both `drawin`s and `client`s. In awesome, Lua code cannot really see this internal class in any way, it just exists to share some of the C code.

So, would you be okay with printing just `button` and `client` in that case? If so, I do not really like this either, because now all objects of a class have the same `tostring` result and cannot be differentiated.

Should I open an issue with rlua and ask them for suggestions on how to do this?

**Comment by psychon** [comment]
Oh, rust is interesting. Something like the following could work:
```rust
println!("tag: {:p}", &tag as *const Tag);
```
Assuming the tag is never cloned, this address should stay constant, right?
And it should not be cloned since otherwise the uservalue is lost.

**Comment by Timidger** [comment]
Correct, that is the way we should print the pointers. I'd like it to be as close as possible, preferably 1-1
