### ISSUE TITLE
Executable naming conflict with AwesomeWM

### ISSUE THREAD

**Issue by AdminXVII** [way-cooler/way-cooler#572]
Not a bug, simply a concern.
Since the last commit, two executables are now generated, way-cooler and awesome. The `awesome` executable should be renamed, as it will cause naming conflict with AwesomeWM, which is made even worse by the fact that they share exactly the same niche.
My humble proposition would be something like `way-cooler-rc` or `wca` (for way-cooler administrator).

**Comment by Elv13** [comment]
Note: The way cooler "awesome" is endorsed by upstream (sidestream?) AwesomeWM as our potential wayland runtime.

It guess the binary could become `awesome_w` and we could eventually rename `awesome` to `awesome_x` and have a dispatch script to detect if wlroot/way-cooler or xorg is running and pick the right executable. That remain to be seen for now the priority is making progress :P

**Comment by psychon** [comment]
I haven't looked at "the current situation", but way-cooler's `awesome` is just a wayland client that connects to the wayland server and does stuff. I would expect this to use some private protocol for communicating with way-cooler and as such it has to be started by way-cooler and cannot be started directly. So... this issue still exists.

**Comment by Timidger** [comment]
Apologies for the delay in replying to this issue.

As @psychon pointed out, the `awesome` binary that Way Cooler uses is just a private client to the compositor and thus can be named whatever it wants. I don't really care what it's called and only called it "awesome" to best distinguish what it did (e.g. awesome does awesome things, way cooler does wayland related things).

Note also that it could be possible in the future for Way Cooler's `awesome` to run against other compositors. For example, the status bar uses the same protocol other windows use to display itself so it's possible to get an Awesome status bar in say Sway or Gnome. So the option of running the `awesome` binary directly should not be disregarded.

**Comment by Timidger** [comment]
> as such it has to be started by way-cooler and cannot be started directly. 

At least for now that's not how it's actually started by the way. Currently we just run them as two binaries, and in fact the `awesome` binary works on other wayland compositors (since there's no custom protocol just yet). This is actually a cool feature I like, because it means you can, for example, use the `awesome` bar and all of its features in Gnome or Sway or whatever. It would be nice to have a check in the code to see if we are in Way Cooler (and thus enable the custom protocols) and if we are not just act like a glorified status bar.

Though if that's not desirable / easy to do because I'm missing something then there's no point to building that in.

Note that there's nothing that _requires_ us to start `awesome` from `way-cooler`, but if we do it the way we are doing now the ability to authenticate that th client trying to control `way-cooler` gets a bit more annoying. It's not impossible however, and I'd probably try to [use this and retain the current setup](https://github.com/swaywm/wlr-protocols/pull/27).

**Comment by Timidger** [comment]
This has been fixed.

`way-cooler` is the compositor binary, the client is named `way-cooler-client`. This can be changed later, but for now this is sufficient to avoid a name conflict.
