### ISSUE TITLE
Design - Class builder and wrappers in awesome APIs

### ISSUE THREAD

**Issue by AdminXVII** [way-cooler/way-cooler#580]
The awesome lua APIs are implemented as wrappers of structs which are built as lua tables dynamically using a class builder. However, RLua allows a native rust-side class system for userdata using the `UserData` trait. I wonder why way-cooler does not use it, as it would be more straight-forward and would maybe leverage RLua-side optimization. My guess is that it is simply because way-cooler copies AwesomeWM's internal system, but I would like to know other motivations behind this choice if there are some.

**Comment by Timidger** [comment]
It's been a long strange trip to where we currently are with the object system in place in Way Cooler. Most of it was motivated by how rlua works, so you might want to read up on the limitations that I've mentioned in another comment here and to read the API docs yourself.

Way Cooler actually [_does_ use the `UserData` trait](https://github.com/way-cooler/way-cooler/search?q=impl+UserData&unscoped_q=impl+UserData) for its objects, We use the class/object builders and traits to make it easier to construct objects, exactly like how C Awesome currently does it.

In particular, [look at the Objectable trait](https://github.com/way-cooler/way-cooler/blob/master/awesome/src/common/object.rs#L92), which abstracts away a lot of boiler plate while also stipulating that the thing it's wrapping implements `UserData`. The reason you won't find it implemented everywhere is because that too has been abstracted out by [this macro](https://github.com/way-cooler/way-cooler/blob/master/awesome/src/macros.rs#L14) (search for uses of it to see how to use it).

The object system is heavily abstracted, perhaps too much so, in both Way Cooler and Awesome. It's a teeny bit easier to use here, but just as confusing when you dig into the details.

**Comment by AdminXVII** [comment]
Thanks for your time.
However, sorry, my question was not asked properly, I was more wondering about the nesting of classes (with for example Tag wrapping an object, wrapping a TagState) and the relative roles of the two wrappers. In my understanding, the top-level wrappers implement a class, the `Object` class serves as a "boilerplate remover" and the lowermost structs are the real state. However, I do not understand the need for the two top-most wrapper, as the classes are native rust + rlua feature and the general code could be implemented as it is for now in a trait, but without the casting and the wrapping.

**Comment by Timidger** [comment]
I'm not 100% sure I'm following, but if you're asking why are we using `AnyUserData` and then casting the type it's because that's the value we get from Lua: it can pass any user data and so we need to cast it to the correct type (or signal an error if it's not what we expect).

If I'm still not understanding, apologies. Perhaps some code examples of your proposed structure would help me understand.

**Comment by AdminXVII** [comment]
Ok now the code follows the structure:
```
pub struct Tag<'lua>(Object<'lua>);
```
                       ↓
```
pub struct Object<'lua> {
    pub object: AnyUserData<'lua>
}
```
                       ↓
```
pub struct TagState {
    name: Option<String>,
    selected: bool,
    activated: bool
}
```

I think this could be expressed as 
```
#[derive(Objectable)]
pub struct Tag {
    name: Option<String>,
    selected: bool,
    activated: bool
}
```
where Objectable provides the same functionalities as it provides now, simply redesigned. I could be wrong as I am fairly new to Rust. However, this would mean
```
fn set_name<'lua>(lua: &'lua Lua,
                  (obj, val): (AnyUserData<'lua>, String))
                  -> rlua::Result<Value<'lua>> {
    let mut tag = Tag::cast(obj.clone().into())?;
    tag.get_object_mut()?.name = Some(val.clone());
    signal::emit_object_signal(lua, obj.into(), "property::name".into(), ())?;
    Ok(Value::Nil)
}
````
would then become
```
fn set_name<'lua>(lua: &'lua Lua,
                  (tag, val): (Tag, String))
                  -> rlua::Result<Value<'lua>> {
    tag.name = Some(val.clone());
    signal::emit_object_signal(lua, &tag, "property::name".into(), ())?;
    Ok(Value::Nil)
}
```
which is a lot more straight-forward (or something along those lines). This would mean we could (I think) drop the Rc and the `is` statements, which Rust warns against and which is slower than compile-time safety.

Moreover, the allocate method could be relocated to the add_methods function, so the code would follow more closely RLua's intent.

So the question is, why this abstraction? I would like to understand the constrains it solves, as it seems to me as more verbose and not following the guidelines of the library.

**Comment by psychon** [comment]
Ahhh, after re-reading, I think my last paragraph is the most important one: `set_user_value`.

You write:

> Concerning AnyUserData, RLua states 'This API should only be used when necessary. Implementing UserData already allows defining methods which check the type and acquire a borrow behind the scenes.', so this means part of the job of Object is already done, and RLua is designed not to use this.

Exercise (I once also tried something like this myself):
Implement the following with rlua:
- You have two kinds of objects, let's say `tag` and `client`.
- Both can be created from lua code via e.g. `tag()` and `client()`.
- A tag has a list of clients that can be set from lua: `t.clients = { c1, c2 }`
- The list of clients can also be "getted": `print(t.clients[1])`

Now make this code work correctly:
```lua
local t = tag()
-- Check that tag really keeps a client and does not just copy it
do
  local c1 = client()
  t.clients = { c1 }
  assert(c1 == t.clients[1])
  local check_real_equality = {}
  check_real_equality[t.clients[1]] = 1
  assert(check_real_equality[c1] == 1)
end
-- Now check for "tag keeps clients alive"
do
  local c1, c2 = client(), client()
  t.clients = { c1, c2 }
end
collectgarbage("collect") -- Just because c1 and c2 are now out of scope
local clients = t.clients
print(clients[1], clients[2], clients[3], clients[1] == clients[2])
```
(Really, try this out, it helps a lot)

Since the clients are Lua objects and since this example is designed so that tags need to keep a reference to clients, you can only really do this with `set_user_value` on `AnyUserData`. One cannot cheat here and just create a new instance refering to the same client, because the `==` and the table index would catch this. Thus, assignment to `clients` needs to be implemented by e.g. having a tag save a table in its `set_user_value`. This table contains all the clients that are saved in the tag.

**Comment by AdminXVII** [comment]
Ok, thanks for your reply. Concerning cloning the RLua documentation states "Implementing UserData already allows defining methods which check the type and acquire a borrow behind the scenes", so I thought cloning the values only meant cloning the rust-side values, all pointing to the same Lua object, thus allowing to change the values in clones but keeping the same references, thus exactly the same lua tables.

It is true though that I'd need to experiment with RLua before really contributing to way-cooler, so will-do.

**Comment by Timidger** [comment]
Thanks for the in depth description @psychon, I'll be sure to point to these comments next time someone asks this.

Gonna go ahead and close this, assuming all your questions are answered @AdminXVII.

**Comment by AdminXVII** [comment]
Yes, this covered it I think.

For the record, this is a minimal, stripped-down, working example of my idea: 
[POC.tar.gz](https://github.com/way-cooler/way-cooler/files/2508823/POC.tar.gz)

**Comment by AdminXVII** [comment]
Don't worry, you sounded just fine. Just to clarify the intent of the code, this was to serve as a base point for future reference, so if someone has this same idea, they can see the problems you mentioned without too much effort, but maybe it wasn't clear enough. Thanks for your detailed remarks as they further illustrate your comment, and they will help as future reference.
