### ISSUE TITLE
Thoughts on Smithhay 0.2

### ISSUE THREAD

**Issue by FriedPandaFries** [way-cooler/way-cooler#606]
### Thoughts On a Pure Rust Compositor

I remember reading your [blog discussing compositor frameworks in 2017](http://way-cooler.org/blog/2017/12/24/way-cooler-2017.html) and recalled you were between wlroots and [Smithay](https://github.com/Smithay/smithay). You dismissed  [Smithay](https://github.com/Smithay/smithay) at the time because they were in early stages of development. 

Now that they have released version 0.2.0 I was wondering if you had reconsidered them as a compositor framework? I think it would be interesting to see a pure rust wayland compositor that is rust from the ground up without bindings and I am curious what your thoughts are.

### Side Note
It would be super cool to install a compositor that's only dependency was rust so you could ...
```sh
cargo install --git https://github.com/way-cooler/way-cooler.git
```

**Comment by Timidger** [comment]
As I said in the blog post:

> I have decided to use wlroots

I have put considerable effort into making safe Rust bindings to wlroots. The effort is still ongoing, but I'm convinced it's better since wlroots is becoming the standard.

"Pure Rust" is not a feature I'm particularly interested in. Working damage tracking, multi output layout, plug and play for standard protocols, a good standard Xwayland implementation, (and the many other features it has which I won't bother listing) are much more important. So far you can write "pure Rust" when using wlroots-rs but if a little C glue code is necessary then I don't consider that a bug (e.g. I foresee custom protocols requiring C code, but that is more due to wayland-rs restrictions than wlroots restrictions)

**Comment by FriedPandaFries** [comment]
Thanks for replying so quickly! I see, I'm very interested in your project. I am looking into throwing Arch linux on an old laptop and making it use rust as much as possible using Way Cooler and [coreutils rewrite](https://github.com/uutils/coreutils). Thank you for making this.

**Comment by Timidger** [comment]
The velocity of wlroots and the velocity of smithay are very, very different.

A large part of this is that wlroots has more developers working on it. There are various reasons for this, but it doesn't really matter since the amount of work smithay must do to achieve its goals is > the amount of work wlroots must do to achieve it's goals. 

So even if smithay started at the point it's at now I would still pitch my tent in wlroots' camp. Because smithay has declared it wants to RiiR everything I'm not interested.

**Comment by AdminXVII** [comment]
@FriedPandaFries If you want truly to be as much Rust as possible and don't need every tool out there, you might want to try [Redox](https://gitlab.redox-os.org/redox-os/redox). It is a UNIX-inspired micro-kernel (not POSIX compliant so you might have some problems with some packages) written entirely with Rust. It works pretty well at the moment though it is limited with hardware support.
